/**
 * PRATICAL PROJECT STEP 01
 * Federal University of Lavras (UFLA)
 * Compilers Discipline
 * 
 * Lexical Analyzer from pratical project step 01 for
 * compilers discipline.
 * 
 * This compiler works with the J-- language, specified
 * by document attached to this software documentation.
 * 
 * by:
 * Lucas Fonseca dos Santos      [201712078]
 * Igor Augusto da Costa Nunes   [201420447]
 * Alan Luz Silveira             [201421560]
 * Igor Emanuel Carvalho da Cruz [201621230]
 * 
 * GITHUB: https://github.com/LucasFonsecadosSantos
 *         https://github.com/Inuness
 *         https://github.com/alanluz
 * 
 */
package app;

import table.LexemeTable;
import table.SymbolTable;
import table.ErrorTable;
import dao.FileHandler;
import utils.Automaton;
import view.GUI;
import model.ErrorType;
import java.util.Map;
import java.util.List;
import java.util.ArrayList;

/**
 * This class represents the LexicalAnalyzer object,
 * the core of project. It contains a automaton and
 * the list with all source code lines.
 * 
 * @author Lucas Fonseca Dos Santos
 * @author Igor Augusto da Costa Nunes
 * @author Alan Luz Silveira
 * @author Igor Emanuel Carvalho da Cruz
 * @version 1.0
 * @since 1.0
 */
public class LexicalAnalyzer {

    /**
     * Automaton attribute
     */
    private Automaton automaton;

    /**
     * Source code data list attribute
     */
    private List<String> sourceCode;

    /**
     * The lexeme table attribute. It is the
     * List<LexemeTable> super class pointer
     * that contains a lot of lexemeTable objects.
     */
    private List<LexemeTable> lexemeTable;

    /**
     * The symbol table attribute, it's the
     * List<SymbolTable> super class pointer that
     * contains a lot of symbolTable objects.
     */
    private List<SymbolTable> symbolTable;

    /**
     * Lexical errors table attributes. This
     * is a List<ErrorTable> super class pointer
     * that contains a lot of ErrorTable objects.
     */
    private List<ErrorTable> errors;

    /**
     * The lexical results table attribute. It contains
     * all results of source code iines analyzer.
     */
    private List<LexicalResults> results;

    /**
     * The lexical analyzer object constructor.
     * It sets the automaton attribute instance and 
     * gets source code data from file with FileHandler
     * static method.
     * 
     * @param fileName The file name string from Main, receid by args from user.
     */
    public LexicalAnalyzer(String fileName) {
        GUI.clear();
        GUI.printActionMessage("Compiling the " + fileName + " code.");
        this.sourceCode = FileHandler.getSourceCode(fileName);
        this.automaton = new Automaton();
        this.lexemeTable = new ArrayList<LexemeTable>();
        this.symbolTable = new ArrayList<SymbolTable>();
        this.results = new ArrayList<LexicalResults>();
        this.errors = new ArrayList<ErrorTable>();
    }

    /**
     * This method is responsible for starting
     * the tokens maker process, sending line by line
     * from source code to automaton.
     * 
     */
    public List[] start() {
        int lineIndex = 0;
        for (String line : this.sourceCode) {
            ++lineIndex;
            LexicalResults result = this.automaton.makeTokens(line, lineIndex);
            if (result != null) {
                this.results.add(result);
            }
        }
        populateTables();
        return new List[] {
            this.lexemeTable, this.symbolTable, this.errors
        };
    }

    /**
     * This method populates all lexical tables resulted by
     * the source code lexical analyze. It gets all objects
     * generated by this and transfers the informations to
     * lexeme table array, symbol table array and
     * errors array.
     */
    private void populateTables() {
        for (LexicalResults results : this.results) {
            this.lexemeTable = results.getLexemeTable();
            this.symbolTable = results.getSymbolTable();
            this.errors = results.getErrors();
        }
    }


}